Import('env', 'arch', 'messaging', 'common', 'gpucommon', 'visionipc')

libs = [common, 'OpenCL', messaging, visionipc, gpucommon]

if arch != "Darwin":
  # xiaomi8: HAL3 path replaces qcom2/spectra. hal3_direct(Android) -> SHM -> camerad_hal_v2(glibc)
  camera_obj = env.Object('cameras/camera_android_hal.cc')
  camera_common_obj = env.Object('cameras/camera_common.cc')
  env.Program('camerad_hal_v2', ['main.cc', camera_obj, camera_common_obj], LIBS=libs)
