Import('env', 'envCython')

common_libs = [
  'params.cc',
  'swaglog.cc',
  'util.cc',
  'ratekeeper.cc',
  'yuv.cc',
]

_common = env.Library('common', common_libs, LIBS="json11")

# xiaomi8: gpucommon (OpenCL utilities) for camerad_hal_v2
_gpucommon = env.Library('gpucommon', ['clutil.cc'])

Export('_common', '_gpucommon')

if GetOption('extras'):
  env.Program('tests/test_common',
              ['tests/test_runner.cc', 'tests/test_util.cc', 'tests/test_swaglog.cc'],
              LIBS=[_common, 'json11', 'zmq', 'pthread'])

# Cython bindings
params_python = envCython.Program('params_pyx.so', 'params_pyx.pyx', LIBS=envCython['LIBS'] + [_common, 'zmq', 'json11'])

common_python = [params_python]

Export('common_python')
