Import('env', 'arch', 'common', 'messaging')

if arch != "Darwin":
  libs = ['usb-1.0', common, messaging, 'pthread']  # xiaomi8: 加回usb-1.0(USB黑panda需)
  panda = env.Library('panda', ['panda.cc', 'panda_comms.cc', 'spi.cc'])

  env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
